# Generated by Django 3.1.2 on 2020-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(choices=[('Select', 'Select'), ('Entertinment', (('Cinema', 'Cinema'), ('Stories', 'Stories'), ('Others', 'Others'))), ('Business', 'Business'), ('Sports', 'Sports'), ('Education', 'Education'), ('Careers', (('IT jobs', 'IT Jobs'), ('Non-IT jobs', 'Non-IT Jobs'), ('Government jobs', 'Government jobs'), ('Others', 'Others'))), ('Hot News', 'Hot News')], default='Select', max_length=50)),
                ('news_headline', models.CharField(max_length=50)),
                ('post_news_text', models.TextField(max_length='500')),
                ('post_news_image', models.FileField(blank=True, null=True, upload_to='app_news/static/Images')),
            ],
        ),
    ]
